### ISSUE TITLE
[Bug]: Mobile Premium does not give premium on web

### ISSUE THREAD

**Issue by Toresean** [MelvorIdle/melvoridle.github.io#1963]
### Describe the bug

Purchased premium on Mobile,  Per the release notes below, premium on the web should have been unlocked. Cloud saves are available on both platforms but only premium on mobile

Mobile Premium Unlock (Mobile to Mobile or Mobile to Web)
Purchasing the Full Version of Melvor Idle on Mobile will now unlock the Full version on other mobile versions, and the web version.

To enable this - log into your Cloud account on a Mobile Device with a valid active purchase. This will enable the Full Version on your Cloud account.

### Reproduction Steps

Purchase Premium on android, create account, log into cloud account on web.  Verify on web that cloud saves are being transferred.  Web doesn't recognize the premium status, and requests that you purchase again.

### Expected behaviour

Premium should be available from the web per the most recent release notes.

### Which platforms are you experiencing this bug on?

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] Mobile App (iOS)
- [X] Mobile App (Android)
- [ ] Steam
- [ ] Other (Please Specify)

### Which version of the game are you experiencing this bug on?

v1.0

### Game Subversion

v1.0.1  ?1415

### Are you using any scripts or extensions?

No

**Comment by MelvorIdle** [comment]
Did you load into the purchased Mobile app while logged into your Cloud account after the update was released?

This is required to enable premium (It isn't retroactive, you need to manually load in to activate it)

**Comment by cutewittlekitty** [comment]
I'm having this exact same problem, I've logged into the cloud forwards backwards side by side and no matter what the web version doesn't recognise the premium bought on mobile.

**Comment by MelvorIdle** [comment]
> I'm having this exact same problem, I've logged into the cloud forwards backwards side by side and no matter what the web version doesn't recognise the premium bought on mobile.

What is your cloud username? I’ll take a look

**Comment by cutewittlekitty** [comment]
cutewittlekitty

**Comment by Toresean** [comment]
I've logged in everyway I can think of and it doesn't seem to change for me either.

cloud username  :  T3chNomad

**Comment by MelvorIdle** [comment]
> cutewittlekitty

I checked your cloud count. There's not link on there.

I tested on my personal account and was able to successfully link my mobile premium to the cloud account.

Make sure you are doing the following:
- Be logged into the same cloud account. Log out of both, and sign in again to be 100% sure
- Make sure the IAP is active and confirmed on mobile.
- Load your cloud account on mobile and wait 10s after PlayFab connection is successful to be sure it links.

**Comment by cutewittlekitty** [comment]
I did that, it still shows no premium on the web page.

**Comment by Toresean** [comment]
Same here, just did the steps above,  Mobile is fully unlocked,  web is locked.

**Comment by MelvorIdle** [comment]
Are you by chance on the paid app on Android? Not the free app with IAP?

**Comment by Toresean** [comment]
Purchased it from the google play store.  Sounds like that is the paid app?

**Comment by Toresean** [comment]
Order history in my google account shows  :  
Upgrade to Premium
I don't remember if I did it in app or from the store.

**Comment by MelvorIdle** [comment]
I have just pushed an update to the game. Did you want to load up now and see if it links?

Be sure to load the android app first then load the browser after.

If it doesn’t work again, let me know and I’ll do some more digging

**Comment by Toresean** [comment]
Just tried it again, 
Steps Taken:  Closed Mobile app,  Closed Web Browser
Opened Mobile app  ( version 1.0.1 ?1415 ) shows connected and everything unlocked.
Launched Web browser, logged in to cloud account,  first screen shows option to upgrade by buying on steam. Still locked.

PlayFab and Melvor cloud connection status green.

**Comment by MelvorIdle** [comment]
Hmm, it should be version ?1416

**Comment by Toresean** [comment]
Web browser shows  V1.0.1  ( ?1417 )
Mobile app V1.0.1 (?1415) no pending update from google play store

**Comment by MelvorIdle** [comment]
Close out of the android app for 10 seconds and see if you can load into the same version as browser. 

From what you mentioned above I don’t think this fix will work for you if you got the in app purchase version, but worth a shot.

definitely need to load above version 1415

**Comment by Toresean** [comment]
Uninstalled and reinstalled app :  New version v1.0.1 (?1417)
Let mobile app run for about a min, did a force save to cloud.
Launched browser in Private Mode,  logged into Web
Web version still locked requesting full upgrade by purchasing on Steam.

**Comment by MelvorIdle** [comment]
I have pushed another fix for this (?1418).

I believe this fix may have resolved the issue. Please let me know if it worked for you. (Will need to load into Android first to activate it)

**Comment by cutewittlekitty** [comment]
I still don't have it on web

**Comment by warslaughter** [comment]
I purchased the full android app (not IAP upgrade) and the web version does not work for me either. Username Warslaughter

**Comment by Toresean** [comment]
Still Not working.
Logged into Mobile version  v1.0.1 ( ?1419)  Let it run for about a minute
Logged into web,  Version v1.0.1 (?1419)   web version still showing the locked version, with option to purchase full version.

**Comment by Toresean** [comment]
Now Working.

Logged back into the mobile version after a clean install, then tested Web, Web version is now unlocked. It appears that it is now working for me.

**Comment by cutewittlekitty** [comment]
Even reinstalling didn't register it for me

**Comment by Deminghuman** [comment]
I tried the above and it's not working either. Not recognizing my purchase on web, asking me to buy it on Steam.

**Comment by tezzy808** [comment]
I kind of have the same issue.  I'm running v1.0.1 ( ?1419) and I purchased the premium/full version on Android.  (I did not upgrade from the 'free' version)

~80% of the time when I log into web version I see the "Upgrade to Premium" link.  I've tried logging out then back in multiple times in succession (while having the Android app active) and it doesn't work.

x-time later... I'll try again then out of the blue, it will work (yay!) and I won't sign out unless I need to restart my PC and I'm back to the where I was before of being asked to upgrade to premium.
